# Generated by Django 4.2 on 2024-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skills",
            old_name="name",
            new_name="ability",
        ),
        migrations.RemoveField(
            model_name="skills",
            name="icon",
        ),
        migrations.AddField(
            model_name="skills",
            name="skill_name",
            field=models.CharField(default="OK", max_length=50),
            preserve_default=False,
        ),
    ]
